import type { Destination } from "./storage";

export const PREFERENCE_OPTIONS = [
  "Biển",
  "Núi",
  "Thành phố",
  "Văn hóa",
  "Ẩm thực",
  "Phiêu lưu",
  "Nghỉ dưỡng",
  "Thiên nhiên",
  "Lịch sử",
  "Mua sắm",
  "Giải trí đêm",
  "Nhiếp ảnh",
];

export const CATEGORIES = [
  "Biển",
  "Núi",
  "Thành phố",
  "Văn hóa",
  "Thiên nhiên",
  "Phiêu lưu",
  "Lịch sử",
];

export const BUDGET_OPTIONS = [
  "< 2 triệu",
  "2-5 triệu",
  "5-10 triệu",
  "10-20 triệu",
  "> 20 triệu",
];

export const SEED_DESTINATIONS: Destination[] = [
  {
    id: "dest_1",
    name: "Vịnh Hạ Long",
    description:
      "Vịnh Hạ Long là Di sản Thế giới UNESCO với hàng nghìn đảo đá vôi và hang động kỳ vĩ. Vịnh rộng khoảng 1.553 km², bao gồm 1.960-2.000 hòn đảo lớn nhỏ. Cảnh quan ngoạn mục với những cột đá vôi sừng sững khiến nơi đây trở thành một trong những điểm du lịch hấp dẫn nhất Việt Nam.",
    images: [
      "https://images.unsplash.com/photo-1528127269322-539801943592?w=800",
      "https://images.unsplash.com/photo-1573790387438-4da905039392?w=800",
    ],
    category: "Thiên nhiên",
    address: "Tỉnh Quảng Ninh, Việt Nam",
    latitude: 20.9101,
    longitude: 107.1839,
    rating: 4.8,
    reviewCount: 2456,
    priceRange: "5-10 triệu",
    tags: ["UNESCO", "Du thuyền", "Chèo kayak", "Hang động"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Du thuyền qua hàng nghìn đảo đá vôi",
      "Khám phá hang Sửng Sốt, hang Đầu Gỗ",
      "Chèo kayak giữa các đảo",
      "Tắm biển tại bãi Ti Tốp",
      "Ngắm hoàng hôn trên vịnh",
    ],
    tips: [
      "Nên đi tour 2 ngày 1 đêm để trải nghiệm trọn vẹn",
      "Mùa đẹp nhất: tháng 10 đến tháng 4",
      "Mang theo kem chống nắng và mũ rộng vành",
      "Đặt tour du thuyền trước ít nhất 1 tuần",
    ],
    bestTimeToVisit: "Tháng 10 - Tháng 4",
    estimatedCostPerPerson: 2500000,
    sampleReviews: [
      { author: "Minh Tuấn", rating: 5, comment: "Cảnh đẹp tuyệt vời, du thuyền sang trọng. Đi 2 ngày 1 đêm rất đáng!", source: "Google" },
      { author: "Thu Hà", rating: 4, comment: "Hang Sửng Sốt rất ấn tượng. Nên đi vào mùa thu để tránh đông đúc.", source: "TripAdvisor" },
      { author: "David N.", rating: 5, comment: "One of the most beautiful places I've ever visited. Kayaking was amazing!", source: "Google" },
      { author: "Lan Phương", rating: 4, comment: "Chèo kayak rất thú vị, nước biển trong xanh. Giá hơi cao nhưng đáng tiền.", source: "TripAdvisor" },
    ],
    nearbyFood: [
      { name: "Nhà hàng Hải sản Hạ Long", address: "Bãi Cháy, Hạ Long", latitude: 20.9550, longitude: 107.0720, costPerPerson: 300000, cuisine: "Hải sản" },
      { name: "Quán Chả mực Hạ Long", address: "Trần Hưng Đạo, Bãi Cháy", latitude: 20.9540, longitude: 107.0680, costPerPerson: 150000, cuisine: "Đặc sản" },
    ],
  },
  {
    id: "dest_2",
    name: "Phố cổ Hội An",
    description:
      "Hội An là một ví dụ điển hình về cảng thương mại Đông Nam Á từ thế kỷ 15 đến 19, được UNESCO công nhận. Kiến trúc và quy hoạch đường phố phản ánh sự giao thoa văn hóa bản địa và nước ngoài. Thành phố là một bảo tàng sống về kiến trúc, ẩm thực và di sản văn hóa.",
    images: [
      "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800",
      "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800",
    ],
    category: "Văn hóa",
    address: "Hội An, Quảng Nam, Việt Nam",
    latitude: 15.8801,
    longitude: 108.338,
    rating: 4.7,
    reviewCount: 1893,
    priceRange: "2-5 triệu",
    tags: ["UNESCO", "Đèn lồng", "May đo", "Ẩm thực"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Dạo phố cổ ngắm đèn lồng về đêm",
      "Thả hoa đăng trên sông Hoài",
      "Thưởng thức Cao Lầu, Mì Quảng, Bánh Mì",
      "May đo quần áo tại các tiệm nổi tiếng",
      "Tham quan Chùa Cầu Nhật Bản",
    ],
    tips: [
      "Nên đi bộ hoặc đạp xe quanh phố cổ",
      "Buổi tối phố cổ đẹp nhất khi đèn lồng sáng",
      "Mua vé tham quan phố cổ: 120.000 VND",
      "Tránh mùa mưa tháng 10-11",
    ],
    bestTimeToVisit: "Tháng 2 - Tháng 5",
    estimatedCostPerPerson: 800000,
    sampleReviews: [
      { author: "Hương Giang", rating: 5, comment: "Phố cổ về đêm đẹp lung linh! Ẩm thực tuyệt vời, đặc biệt là Cao Lầu.", source: "Google" },
      { author: "John M.", rating: 5, comment: "Amazing ancient town! The lanterns at night are magical. Must try the local food.", source: "TripAdvisor" },
      { author: "Thanh Tùng", rating: 4, comment: "Nên đi vào ngày thường, cuối tuần rất đông. Bánh mì Phượng ngon tuyệt!", source: "Google" },
    ],
    nearbyFood: [
      { name: "Bánh Mì Phượng", address: "2B Phan Châu Trinh, Hội An", latitude: 15.8775, longitude: 108.3280, costPerPerson: 30000, cuisine: "Bánh mì" },
      { name: "Cao Lầu Thanh", address: "26 Thái Phiên, Hội An", latitude: 15.8790, longitude: 108.3350, costPerPerson: 50000, cuisine: "Đặc sản" },
      { name: "Quán Cơm gà Bà Buội", address: "22 Phan Châu Trinh, Hội An", latitude: 15.8778, longitude: 108.3290, costPerPerson: 60000, cuisine: "Cơm gà" },
    ],
  },
  {
    id: "dest_3",
    name: "Sa Pa",
    description:
      "Sa Pa là thị trấn nằm trong dãy Hoàng Liên Sơn, tây bắc Việt Nam. Đây là điểm xuất phát cho nhiều hành trình trekking, nhìn xuống thung lũng Mường Hoa với ruộng bậc thang tuyệt đẹp. Vùng đất là quê hương của các dân tộc thiểu số như H'Mông và Dao, mang đến trải nghiệm văn hóa độc đáo.",
    images: [
      "https://images.unsplash.com/photo-1570366583862-f91883984fde?w=800",
      "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800",
    ],
    category: "Núi",
    address: "Tỉnh Lào Cai, Việt Nam",
    latitude: 22.3364,
    longitude: 103.8438,
    rating: 4.6,
    reviewCount: 1567,
    priceRange: "2-5 triệu",
    tags: ["Trekking", "Ruộng bậc thang", "Văn hóa", "Núi"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Chinh phục đỉnh Fansipan - Nóc nhà Đông Dương",
      "Trekking qua ruộng bậc thang Mường Hoa",
      "Khám phá bản làng dân tộc H'Mông, Dao",
      "Ngắm mây trên đỉnh núi",
      "Chợ phiên vùng cao",
    ],
    tips: [
      "Mang giày trekking và áo ấm",
      "Nên thuê hướng dẫn viên bản địa",
      "Mùa lúa chín tháng 9-10 đẹp nhất",
      "Cẩn thận đường trơn khi mưa",
    ],
    bestTimeToVisit: "Tháng 9 - Tháng 11, Tháng 3 - Tháng 5",
    estimatedCostPerPerson: 1200000,
    sampleReviews: [
      { author: "Việt Anh", rating: 5, comment: "Trekking Mường Hoa tuyệt đẹp! Người dân tộc rất thân thiện, phong cảnh hùng vĩ.", source: "Google" },
      { author: "Sarah L.", rating: 4, comment: "Stunning rice terraces! The homestay experience was unforgettable. Bring warm clothes!", source: "TripAdvisor" },
      { author: "Hoàng Nam", rating: 4, comment: "Fansipan đi cáp treo rất nhanh, view cực đẹp. Nên đi vào mùa lúa chín.", source: "Google" },
    ],
    nearbyFood: [
      { name: "Nhà hàng Thắng cố Sa Pa", address: "Trung tâm Sa Pa", latitude: 22.3370, longitude: 103.8440, costPerPerson: 80000, cuisine: "Đặc sản vùng cao" },
      { name: "Quán Lợn cắp nách", address: "Fansipan, Sa Pa", latitude: 22.3350, longitude: 103.8420, costPerPerson: 120000, cuisine: "Đặc sản" },
    ],
  },
  {
    id: "dest_4",
    name: "Đảo Phú Quốc",
    description:
      "Phú Quốc là hòn đảo lớn nhất Việt Nam, nổi tiếng với bãi biển cát trắng, rạn san hô và rừng nhiệt đới. Đảo mang đến sự kết hợp hoàn hảo giữa nghỉ dưỡng và phiêu lưu với các hoạt động lặn biển, snorkeling và tham quan nhà thùng nước mắm nổi tiếng.",
    images: [
      "https://images.unsplash.com/photo-1559628376-f3fe5f782a2e?w=800",
      "https://images.unsplash.com/photo-1540611025311-01df3cee54b5?w=800",
    ],
    category: "Biển",
    address: "Tỉnh Kiên Giang, Việt Nam",
    latitude: 10.2899,
    longitude: 103.984,
    rating: 4.5,
    reviewCount: 2103,
    priceRange: "5-10 triệu",
    tags: ["Biển", "Lặn biển", "Hoàng hôn", "Hải sản"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Ngắm hoàng hôn tại bãi Dài",
      "Lặn ngắm san hô tại An Thới",
      "Tham quan VinWonders Phú Quốc",
      "Khám phá làng chài Hàm Ninh",
      "Thưởng thức hải sản tươi sống",
    ],
    tips: [
      "Mùa khô tháng 11-4 là thời điểm lý tưởng",
      "Thuê xe máy để di chuyển trên đảo",
      "Đừng bỏ lỡ nước mắm Phú Quốc chính gốc",
      "Bãi Sao là bãi biển đẹp nhất đảo",
    ],
    bestTimeToVisit: "Tháng 11 - Tháng 4",
    estimatedCostPerPerson: 2000000,
    sampleReviews: [
      { author: "Quỳnh Anh", rating: 5, comment: "Bãi Sao đẹp không thua Maldives! Hải sản tươi ngon, giá phải chăng.", source: "Google" },
      { author: "Mark T.", rating: 4, comment: "Beautiful beaches, great snorkeling. VinWonders is fun for families. Rent a scooter!", source: "TripAdvisor" },
      { author: "Đức Minh", rating: 5, comment: "Hoàng hôn ở bãi Dài đẹp nhất Việt Nam! Lặn ngắm san hô An Thới rất đáng.", source: "Google" },
    ],
    nearbyFood: [
      { name: "Quán Crab House", address: "Đường Trần Hưng Đạo, Dương Đông", latitude: 10.2150, longitude: 103.9600, costPerPerson: 250000, cuisine: "Hải sản" },
      { name: "Bún quậy Phú Quốc", address: "Chợ đêm Dinh Cậu", latitude: 10.2130, longitude: 103.9580, costPerPerson: 50000, cuisine: "Đặc sản" },
    ],
  },
  {
    id: "dest_5",
    name: "Đà Nẵng",
    description:
      "Đà Nẵng là thành phố ven biển miền Trung Việt Nam với những bãi biển cát trắng dài. Đây là cửa ngõ đến Ngũ Hành Sơn - năm ngọn đồi đá vôi và cẩm thạch với hang động và tượng Phật. Cầu Rồng và Bà Nà Hills là những điểm tham quan không thể bỏ qua.",
    images: [
      "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800",
      "https://images.unsplash.com/photo-1464817739973-0128fe77aaa1?w=800",
    ],
    category: "Thành phố",
    address: "Đà Nẵng, Việt Nam",
    latitude: 16.0544,
    longitude: 108.2022,
    rating: 4.5,
    reviewCount: 1789,
    priceRange: "2-5 triệu",
    tags: ["Biển", "Cầu Rồng", "Bà Nà Hills", "Ngũ Hành Sơn"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Xem Cầu Rồng phun lửa cuối tuần",
      "Tham quan Bà Nà Hills và Cầu Vàng",
      "Tắm biển Mỹ Khê - top bãi biển đẹp nhất",
      "Khám phá Ngũ Hành Sơn",
      "Thưởng thức bún chả cá, mì Quảng",
    ],
    tips: [
      "Cầu Rồng phun lửa lúc 21h thứ 7 và Chủ nhật",
      "Nên đi Bà Nà Hills vào ngày nắng",
      "Bãi biển Mỹ Khê miễn phí",
      "Kết hợp đi Hội An chỉ 30 phút lái xe",
    ],
    bestTimeToVisit: "Tháng 3 - Tháng 8",
    estimatedCostPerPerson: 1500000,
    sampleReviews: [
      { author: "Phương Linh", rating: 5, comment: "Cầu Vàng đẹp ảo diệu! Bà Nà Hills rất đáng để dành 1 ngày. Nên mua vé online rẻ hơn.", source: "Google" },
      { author: "Tom B.", rating: 4, comment: "Great city with amazing beaches. Dragon Bridge fire show on weekends is a must-see!", source: "TripAdvisor" },
      { author: "Hải Yến", rating: 5, comment: "Bãi biển Mỹ Khê sạch và đẹp. Bún chả cá đặc sản phải thử!", source: "Google" },
    ],
    nearbyFood: [
      { name: "Quán Bún chả cá 109", address: "109 Nguyễn Chí Thanh, Đà Nẵng", latitude: 16.0680, longitude: 108.2100, costPerPerson: 40000, cuisine: "Bún chả cá" },
      { name: "Mì Quảng Bà Vị", address: "166 Lê Đình Dương, Đà Nẵng", latitude: 16.0640, longitude: 108.2150, costPerPerson: 35000, cuisine: "Mì Quảng" },
      { name: "Bánh xèo Bà Dưỡng", address: "K280/23 Hoàng Diệu, Đà Nẵng", latitude: 16.0600, longitude: 108.2080, costPerPerson: 45000, cuisine: "Bánh xèo" },
    ],
  },
  {
    id: "dest_6",
    name: "Ninh Bình",
    description:
      "Ninh Bình được mệnh danh là 'Vịnh Hạ Long trên cạn' với cảnh quan núi đá vôi kỳ vĩ. Tỉnh có cố đô Hoa Lư, Quần thể danh thắng Tràng An (UNESCO) và Tam Cốc với hành trình thuyền qua hang động và đồng lúa.",
    images: [
      "https://images.unsplash.com/photo-1573790387438-4da905039392?w=800",
      "https://images.unsplash.com/photo-1528127269322-539801943592?w=800",
    ],
    category: "Thiên nhiên",
    address: "Tỉnh Ninh Bình, Việt Nam",
    latitude: 20.2506,
    longitude: 105.9745,
    rating: 4.6,
    reviewCount: 1234,
    priceRange: "2-5 triệu",
    tags: ["UNESCO", "Thuyền", "Hang động", "Chùa"],
    openHours: "6:00 - 18:00",
    isActive: true,
    highlights: [
      "Đi thuyền qua Tràng An ngắm hang động",
      "Thăm cố đô Hoa Lư",
      "Leo 500 bậc lên đỉnh Hang Múa",
      "Khám phá Tam Cốc - Bích Động",
      "Tham quan chùa Bái Đính - ngôi chùa lớn nhất Việt Nam",
    ],
    tips: [
      "Nên đi vào mùa lúa chín (tháng 5-6) để ngắm cảnh đẹp nhất",
      "Mang giày thoải mái vì đi bộ nhiều",
      "Tour thuyền Tràng An khoảng 2-3 giờ",
      "Có thể kết hợp đi trong ngày từ Hà Nội",
    ],
    bestTimeToVisit: "Tháng 5 - Tháng 6, Tháng 9 - Tháng 10",
    estimatedCostPerPerson: 600000,
    sampleReviews: [
      { author: "Trung Kiên", rating: 5, comment: "Tràng An đẹp không kém Hạ Long! Đi thuyền qua hang rất thú vị, nước trong xanh.", source: "Google" },
      { author: "Emma W.", rating: 5, comment: "Hang Mua viewpoint is absolutely stunning! Trang An boat ride was the highlight of our Vietnam trip.", source: "TripAdvisor" },
      { author: "Bích Ngọc", rating: 4, comment: "Cảnh đẹp nhưng leo Hang Múa khá vất vả. Nên đi sáng sớm tránh nóng.", source: "Google" },
    ],
    nearbyFood: [
      { name: "Cơm cháy Ninh Bình", address: "Ninh Hải, Hoa Lư", latitude: 20.2600, longitude: 105.9700, costPerPerson: 70000, cuisine: "Đặc sản" },
      { name: "Quán Dê núi Ninh Bình", address: "TP Ninh Bình", latitude: 20.2530, longitude: 105.9750, costPerPerson: 150000, cuisine: "Thịt dê" },
    ],
  },
  {
    id: "dest_7",
    name: "Đà Lạt",
    description:
      "Được mệnh danh là 'Thành phố mùa xuân vĩnh cửu', Đà Lạt nằm trên cao nguyên Trung Bộ Việt Nam. Nổi tiếng với kiến trúc Pháp, vườn hoa, hồ và thác nước, Đà Lạt có khí hậu mát mẻ quanh năm và không khí lãng mạn hoàn hảo cho các cặp đôi.",
    images: [
      "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800",
      "https://images.unsplash.com/photo-1570366583862-f91883984fde?w=800",
    ],
    category: "Núi",
    address: "Tỉnh Lâm Đồng, Việt Nam",
    latitude: 11.9404,
    longitude: 108.4583,
    rating: 4.4,
    reviewCount: 1678,
    priceRange: "2-5 triệu",
    tags: ["Hoa", "Thác nước", "Cà phê", "Lãng mạn"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Check-in tại Hồ Xuân Hương",
      "Tham quan vườn hoa thành phố",
      "Thưởng thức cà phê Đà Lạt",
      "Khám phá Thác Datanla bằng máng trượt",
      "Đi chợ đêm Đà Lạt",
    ],
    tips: [
      "Mang áo ấm vì trời lạnh về đêm",
      "Thuê xe máy là cách tốt nhất để khám phá",
      "Đừng bỏ lỡ bánh tráng nướng chợ đêm",
      "Săn mây Langbiang vào sáng sớm",
    ],
    bestTimeToVisit: "Tháng 11 - Tháng 3",
    estimatedCostPerPerson: 1000000,
    sampleReviews: [
      { author: "Ngọc Trâm", rating: 5, comment: "Đà Lạt lãng mạn quá! Cà phê ngon, thời tiết mát mẻ. Chợ đêm vui và rẻ.", source: "Google" },
      { author: "Alex K.", rating: 4, comment: "Beautiful hill station! The Crazy House is unique. Great coffee everywhere. Bring warm clothes!", source: "TripAdvisor" },
      { author: "Thành Đạt", rating: 5, comment: "Săn mây Langbiang lúc 5h sáng, cảnh tuyệt đẹp! Bánh tráng nướng chợ đêm ngon.", source: "Google" },
    ],
    nearbyFood: [
      { name: "Bánh tráng nướng chợ đêm", address: "Chợ đêm Đà Lạt", latitude: 11.9430, longitude: 108.4380, costPerPerson: 25000, cuisine: "Ăn vặt" },
      { name: "Quán Lẩu gà lá é", address: "Phan Đình Phùng, Đà Lạt", latitude: 11.9450, longitude: 108.4400, costPerPerson: 100000, cuisine: "Lẩu" },
      { name: "Tiệm cà phê Mê Linh", address: "20 Trần Hưng Đạo, Đà Lạt", latitude: 11.9380, longitude: 108.4350, costPerPerson: 40000, cuisine: "Cà phê" },
    ],
  },
  {
    id: "dest_8",
    name: "Kinh thành Huế",
    description:
      "Kinh thành Huế là pháo đài và cung điện có tường bao trong cố đô Việt Nam. Là Di sản Thế giới UNESCO, nơi đây từng là trung tâm quyền lực của triều Nguyễn từ 1802 đến 1945. Quần thể bao gồm Tử Cấm Thành, lăng tẩm hoàng gia và các ngôi chùa cổ.",
    images: [
      "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800",
      "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800",
    ],
    category: "Lịch sử",
    address: "Huế, Thừa Thiên Huế, Việt Nam",
    latitude: 16.4698,
    longitude: 107.5792,
    rating: 4.5,
    reviewCount: 1456,
    priceRange: "< 2 triệu",
    tags: ["UNESCO", "Cung điện", "Lịch sử", "Kiến trúc"],
    openHours: "7:00 - 17:30",
    isActive: true,
    highlights: [
      "Tham quan Đại Nội - Tử Cấm Thành",
      "Thăm các lăng tẩm: Minh Mạng, Tự Đức, Khải Định",
      "Du thuyền trên sông Hương",
      "Thưởng thức ẩm thực cung đình Huế",
      "Ngắm Cầu Trường Tiền về đêm",
    ],
    tips: [
      "Mua vé combo tham quan nhiều điểm tiết kiệm hơn",
      "Nên thuê hướng dẫn viên để hiểu lịch sử",
      "Thử bún bò Huế chính gốc",
      "Tránh giờ trưa nắng khi tham quan",
    ],
    bestTimeToVisit: "Tháng 1 - Tháng 4",
    estimatedCostPerPerson: 500000,
    sampleReviews: [
      { author: "Khánh Linh", rating: 5, comment: "Kinh thành Huế rất hoành tráng! Nên thuê guide để hiểu lịch sử. Bún bò Huế ngon tuyệt.", source: "Google" },
      { author: "Pierre D.", rating: 4, comment: "Rich history and beautiful architecture. The Forbidden Purple City is fascinating. Great local cuisine!", source: "TripAdvisor" },
      { author: "Minh Châu", rating: 4, comment: "Lăng Khải Định kiến trúc rất đặc biệt. Du thuyền sông Hương buổi chiều rất thư giãn.", source: "Google" },
    ],
    nearbyFood: [
      { name: "Bún bò Huế Bà Tuyết", address: "47 Nguyễn Công Trứ, Huế", latitude: 16.4650, longitude: 107.5850, costPerPerson: 35000, cuisine: "Bún bò" },
      { name: "Cơm Hến Huế", address: "Trần Hưng Đạo, Huế", latitude: 16.4680, longitude: 107.5800, costPerPerson: 25000, cuisine: "Đặc sản" },
      { name: "Bánh bèo Huế", address: "Chợ Đông Ba, Huế", latitude: 16.4720, longitude: 107.5830, costPerPerson: 30000, cuisine: "Bánh Huế" },
    ],
  },
  {
    id: "dest_9",
    name: "Nha Trang",
    description:
      "Nha Trang là thành phố biển phía nam Việt Nam nổi tiếng với bãi biển đẹp, các điểm lặn biển và đảo ngoài khơi. Thành phố có cuộc sống về đêm sôi động, nhà hàng hải sản và di tích Chăm cổ. VinWonders trên đảo Hòn Tre là điểm tham quan hàng đầu.",
    images: [
      "https://images.unsplash.com/photo-1559628376-f3fe5f782a2e?w=800",
      "https://images.unsplash.com/photo-1540611025311-01df3cee54b5?w=800",
    ],
    category: "Biển",
    address: "Tỉnh Khánh Hòa, Việt Nam",
    latitude: 12.2388,
    longitude: 109.1967,
    rating: 4.3,
    reviewCount: 1890,
    priceRange: "2-5 triệu",
    tags: ["Biển", "Lặn biển", "Đảo", "Giải trí đêm"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Lặn ngắm san hô tại Hòn Mun",
      "Tham quan VinWonders Nha Trang",
      "Tắm bùn khoáng nóng",
      "Tour 4 đảo bằng tàu",
      "Khám phá Tháp Bà Ponagar",
    ],
    tips: [
      "Mùa biển đẹp nhất từ tháng 6 đến tháng 9",
      "Nên đặt tour lặn biển trước",
      "Tắm bùn I-Resort là trải nghiệm phải thử",
      "Chợ Đầm là nơi mua hải sản tươi",
    ],
    bestTimeToVisit: "Tháng 6 - Tháng 9",
    estimatedCostPerPerson: 1500000,
    sampleReviews: [
      { author: "Thùy Dung", rating: 4, comment: "Biển Nha Trang đẹp, tắm bùn rất thư giãn. Tour 4 đảo vui nhưng hơi ồn.", source: "Google" },
      { author: "James R.", rating: 5, comment: "Amazing diving at Hon Mun! The mud baths are a unique experience. Great nightlife too.", source: "TripAdvisor" },
      { author: "Bảo Long", rating: 4, comment: "VinWonders rất rộng, nên dành cả ngày. Hải sản chợ Đầm tươi ngon giá rẻ.", source: "Google" },
    ],
    nearbyFood: [
      { name: "Nhà hàng Hải sản Nha Trang", address: "Trần Phú, Nha Trang", latitude: 12.2450, longitude: 109.1950, costPerPerson: 200000, cuisine: "Hải sản" },
      { name: "Bún cá sứa Nha Trang", address: "Chợ Đầm, Nha Trang", latitude: 12.2400, longitude: 109.1930, costPerPerson: 40000, cuisine: "Đặc sản" },
    ],
  },
  {
    id: "dest_10",
    name: "Phong Nha - Kẻ Bàng",
    description:
      "Vườn Quốc gia Phong Nha-Kẻ Bàng là Di sản Thế giới UNESCO, nơi có hang Sơn Đoòng - hang động lớn nhất thế giới. Vườn quốc gia sở hữu hệ thống hang động ngoạn mục, sông ngầm và rừng nguyên sinh. Những người yêu mạo hiểm có thể khám phá các hang động từ dễ đến hành trình nhiều ngày.",
    images: [
      "https://images.unsplash.com/photo-1573790387438-4da905039392?w=800",
      "https://images.unsplash.com/photo-1528127269322-539801943592?w=800",
    ],
    category: "Phiêu lưu",
    address: "Tỉnh Quảng Bình, Việt Nam",
    latitude: 17.5922,
    longitude: 106.2834,
    rating: 4.7,
    reviewCount: 987,
    priceRange: "5-10 triệu",
    tags: ["UNESCO", "Hang động", "Phiêu lưu", "Rừng"],
    openHours: "7:00 - 16:30",
    isActive: true,
    highlights: [
      "Khám phá Động Phong Nha bằng thuyền",
      "Tham quan Động Thiên Đường",
      "Zipline qua sông tại Dark Cave",
      "Trekking trong rừng quốc gia",
      "Tour hang Sơn Đoòng (đặt trước 1 năm)",
    ],
    tips: [
      "Đặt tour Sơn Đoòng cần trước 6-12 tháng",
      "Dark Cave là trải nghiệm vui nhất cho nhóm",
      "Mang đồ chống nước cho các hoạt động hang động",
      "Mùa khô tháng 4-8 là thời điểm tốt nhất",
    ],
    bestTimeToVisit: "Tháng 4 - Tháng 8",
    estimatedCostPerPerson: 1800000,
    sampleReviews: [
      { author: "Đình Khoa", rating: 5, comment: "Động Thiên Đường đẹp ngoài sức tưởng tượng! Dark Cave cực kỳ vui cho nhóm bạn.", source: "Google" },
      { author: "Lisa M.", rating: 5, comment: "Most incredible caves I've ever seen! The zipline at Dark Cave is thrilling. Book tours early!", source: "TripAdvisor" },
      { author: "Công Danh", rating: 4, comment: "Phong Nha rất đẹp và hoang sơ. Nên thuê xe máy từ Đồng Hới ra. Tour thuyền rất hay.", source: "Google" },
    ],
    nearbyFood: [
      { name: "Quán Cháo canh Phong Nha", address: "Sơn Trạch, Bố Trạch", latitude: 17.5900, longitude: 106.2800, costPerPerson: 50000, cuisine: "Đặc sản" },
      { name: "Nhà hàng Pepper House", address: "Phong Nha, Quảng Bình", latitude: 17.5910, longitude: 106.2820, costPerPerson: 80000, cuisine: "Việt - Âu" },
    ],
  },
];

export const SEED_ADMIN: {
  username: string;
  password: string;
  email: string;
  fullName: string;
  role: "admin";
} = {
  username: "admin",
  password: "admin123",
  email: "admin@plango.vn",
  fullName: "PlanGo Admin",
  role: "admin",
};
