import type { Destination } from "./storage";

export const PREFERENCE_OPTIONS = [
  "Biển",
  "Núi",
  "Thành phố",
  "Văn hóa",
  "Ẩm thực",
  "Phiêu lưu",
  "Nghỉ dưỡng",
  "Thiên nhiên",
  "Lịch sử",
  "Mua sắm",
  "Giải trí đêm",
  "Nhiếp ảnh",
];

export const CATEGORIES = [
  "Biển",
  "Núi",
  "Thành phố",
  "Văn hóa",
  "Thiên nhiên",
  "Phiêu lưu",
  "Lịch sử",
];

export const BUDGET_OPTIONS = [
  "< 2 triệu",
  "2-5 triệu",
  "5-10 triệu",
  "10-20 triệu",
  "> 20 triệu",
];

export const SEED_DESTINATIONS: Destination[] = [
  {
    id: "dest_1",
    name: "Vịnh Hạ Long",
    description:
      "Vịnh Hạ Long là Di sản Thế giới UNESCO với hàng nghìn đảo đá vôi và hang động kỳ vĩ. Vịnh rộng khoảng 1.553 km², bao gồm 1.960-2.000 hòn đảo lớn nhỏ. Cảnh quan ngoạn mục với những cột đá vôi sừng sững khiến nơi đây trở thành một trong những điểm du lịch hấp dẫn nhất Việt Nam.",
    images: [
      "https://images.unsplash.com/photo-1528127269322-539801943592?w=800",
      "https://images.unsplash.com/photo-1573790387438-4da905039392?w=800",
    ],
    category: "Thiên nhiên",
    address: "Tỉnh Quảng Ninh, Việt Nam",
    latitude: 20.9101,
    longitude: 107.1839,
    rating: 4.8,
    reviewCount: 2456,
    priceRange: "5-10 triệu",
    tags: ["UNESCO", "Du thuyền", "Chèo kayak", "Hang động"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Du thuyền qua hàng nghìn đảo đá vôi",
      "Khám phá hang Sửng Sốt, hang Đầu Gỗ",
      "Chèo kayak giữa các đảo",
      "Tắm biển tại bãi Ti Tốp",
      "Ngắm hoàng hôn trên vịnh",
    ],
    tips: [
      "Nên đi tour 2 ngày 1 đêm để trải nghiệm trọn vẹn",
      "Mùa đẹp nhất: tháng 10 đến tháng 4",
      "Mang theo kem chống nắng và mũ rộng vành",
      "Đặt tour du thuyền trước ít nhất 1 tuần",
    ],
    bestTimeToVisit: "Tháng 10 - Tháng 4",
  },
  {
    id: "dest_2",
    name: "Phố cổ Hội An",
    description:
      "Hội An là một ví dụ điển hình về cảng thương mại Đông Nam Á từ thế kỷ 15 đến 19, được UNESCO công nhận. Kiến trúc và quy hoạch đường phố phản ánh sự giao thoa văn hóa bản địa và nước ngoài. Thành phố là một bảo tàng sống về kiến trúc, ẩm thực và di sản văn hóa.",
    images: [
      "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800",
      "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800",
    ],
    category: "Văn hóa",
    address: "Hội An, Quảng Nam, Việt Nam",
    latitude: 15.8801,
    longitude: 108.338,
    rating: 4.7,
    reviewCount: 1893,
    priceRange: "2-5 triệu",
    tags: ["UNESCO", "Đèn lồng", "May đo", "Ẩm thực"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Dạo phố cổ ngắm đèn lồng về đêm",
      "Thả hoa đăng trên sông Hoài",
      "Thưởng thức Cao Lầu, Mì Quảng, Bánh Mì",
      "May đo quần áo tại các tiệm nổi tiếng",
      "Tham quan Chùa Cầu Nhật Bản",
    ],
    tips: [
      "Nên đi bộ hoặc đạp xe quanh phố cổ",
      "Buổi tối phố cổ đẹp nhất khi đèn lồng sáng",
      "Mua vé tham quan phố cổ: 120.000 VND",
      "Tránh mùa mưa tháng 10-11",
    ],
    bestTimeToVisit: "Tháng 2 - Tháng 5",
  },
  {
    id: "dest_3",
    name: "Sa Pa",
    description:
      "Sa Pa là thị trấn nằm trong dãy Hoàng Liên Sơn, tây bắc Việt Nam. Đây là điểm xuất phát cho nhiều hành trình trekking, nhìn xuống thung lũng Mường Hoa với ruộng bậc thang tuyệt đẹp. Vùng đất là quê hương của các dân tộc thiểu số như H'Mông và Dao, mang đến trải nghiệm văn hóa độc đáo.",
    images: [
      "https://images.unsplash.com/photo-1570366583862-f91883984fde?w=800",
      "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800",
    ],
    category: "Núi",
    address: "Tỉnh Lào Cai, Việt Nam",
    latitude: 22.3364,
    longitude: 103.8438,
    rating: 4.6,
    reviewCount: 1567,
    priceRange: "2-5 triệu",
    tags: ["Trekking", "Ruộng bậc thang", "Văn hóa", "Núi"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Chinh phục đỉnh Fansipan - Nóc nhà Đông Dương",
      "Trekking qua ruộng bậc thang Mường Hoa",
      "Khám phá bản làng dân tộc H'Mông, Dao",
      "Ngắm mây trên đỉnh núi",
      "Chợ phiên vùng cao",
    ],
    tips: [
      "Mang giày trekking và áo ấm",
      "Nên thuê hướng dẫn viên bản địa",
      "Mùa lúa chín tháng 9-10 đẹp nhất",
      "Cẩn thận đường trơn khi mưa",
    ],
    bestTimeToVisit: "Tháng 9 - Tháng 11, Tháng 3 - Tháng 5",
  },
  {
    id: "dest_4",
    name: "Đảo Phú Quốc",
    description:
      "Phú Quốc là hòn đảo lớn nhất Việt Nam, nổi tiếng với bãi biển cát trắng, rạn san hô và rừng nhiệt đới. Đảo mang đến sự kết hợp hoàn hảo giữa nghỉ dưỡng và phiêu lưu với các hoạt động lặn biển, snorkeling và tham quan nhà thùng nước mắm nổi tiếng.",
    images: [
      "https://images.unsplash.com/photo-1559628376-f3fe5f782a2e?w=800",
      "https://images.unsplash.com/photo-1540611025311-01df3cee54b5?w=800",
    ],
    category: "Biển",
    address: "Tỉnh Kiên Giang, Việt Nam",
    latitude: 10.2899,
    longitude: 103.984,
    rating: 4.5,
    reviewCount: 2103,
    priceRange: "5-10 triệu",
    tags: ["Biển", "Lặn biển", "Hoàng hôn", "Hải sản"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Ngắm hoàng hôn tại bãi Dài",
      "Lặn ngắm san hô tại An Thới",
      "Tham quan VinWonders Phú Quốc",
      "Khám phá làng chài Hàm Ninh",
      "Thưởng thức hải sản tươi sống",
    ],
    tips: [
      "Mùa khô tháng 11-4 là thời điểm lý tưởng",
      "Thuê xe máy để di chuyển trên đảo",
      "Đừng bỏ lỡ nước mắm Phú Quốc chính gốc",
      "Bãi Sao là bãi biển đẹp nhất đảo",
    ],
    bestTimeToVisit: "Tháng 11 - Tháng 4",
  },
  {
    id: "dest_5",
    name: "Đà Nẵng",
    description:
      "Đà Nẵng là thành phố ven biển miền Trung Việt Nam với những bãi biển cát trắng dài. Đây là cửa ngõ đến Ngũ Hành Sơn - năm ngọn đồi đá vôi và cẩm thạch với hang động và tượng Phật. Cầu Rồng và Bà Nà Hills là những điểm tham quan không thể bỏ qua.",
    images: [
      "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800",
      "https://images.unsplash.com/photo-1464817739973-0128fe77aaa1?w=800",
    ],
    category: "Thành phố",
    address: "Đà Nẵng, Việt Nam",
    latitude: 16.0544,
    longitude: 108.2022,
    rating: 4.5,
    reviewCount: 1789,
    priceRange: "2-5 triệu",
    tags: ["Biển", "Cầu Rồng", "Bà Nà Hills", "Ngũ Hành Sơn"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Xem Cầu Rồng phun lửa cuối tuần",
      "Tham quan Bà Nà Hills và Cầu Vàng",
      "Tắm biển Mỹ Khê - top bãi biển đẹp nhất",
      "Khám phá Ngũ Hành Sơn",
      "Thưởng thức bún chả cá, mì Quảng",
    ],
    tips: [
      "Cầu Rồng phun lửa lúc 21h thứ 7 và Chủ nhật",
      "Nên đi Bà Nà Hills vào ngày nắng",
      "Bãi biển Mỹ Khê miễn phí",
      "Kết hợp đi Hội An chỉ 30 phút lái xe",
    ],
    bestTimeToVisit: "Tháng 3 - Tháng 8",
  },
  {
    id: "dest_6",
    name: "Ninh Bình",
    description:
      "Ninh Bình được mệnh danh là 'Vịnh Hạ Long trên cạn' với cảnh quan núi đá vôi kỳ vĩ. Tỉnh có cố đô Hoa Lư, Quần thể danh thắng Tràng An (UNESCO) và Tam Cốc với hành trình thuyền qua hang động và đồng lúa.",
    images: [
      "https://images.unsplash.com/photo-1573790387438-4da905039392?w=800",
      "https://images.unsplash.com/photo-1528127269322-539801943592?w=800",
    ],
    category: "Thiên nhiên",
    address: "Tỉnh Ninh Bình, Việt Nam",
    latitude: 20.2506,
    longitude: 105.9745,
    rating: 4.6,
    reviewCount: 1234,
    priceRange: "2-5 triệu",
    tags: ["UNESCO", "Thuyền", "Hang động", "Chùa"],
    openHours: "6:00 - 18:00",
    isActive: true,
    highlights: [
      "Đi thuyền qua Tràng An ngắm hang động",
      "Thăm cố đô Hoa Lư",
      "Leo 500 bậc lên đỉnh Hang Múa",
      "Khám phá Tam Cốc - Bích Động",
      "Tham quan chùa Bái Đính - ngôi chùa lớn nhất Việt Nam",
    ],
    tips: [
      "Nên đi vào mùa lúa chín (tháng 5-6) để ngắm cảnh đẹp nhất",
      "Mang giày thoải mái vì đi bộ nhiều",
      "Tour thuyền Tràng An khoảng 2-3 giờ",
      "Có thể kết hợp đi trong ngày từ Hà Nội",
    ],
    bestTimeToVisit: "Tháng 5 - Tháng 6, Tháng 9 - Tháng 10",
  },
  {
    id: "dest_7",
    name: "Đà Lạt",
    description:
      "Được mệnh danh là 'Thành phố mùa xuân vĩnh cửu', Đà Lạt nằm trên cao nguyên Trung Bộ Việt Nam. Nổi tiếng với kiến trúc Pháp, vườn hoa, hồ và thác nước, Đà Lạt có khí hậu mát mẻ quanh năm và không khí lãng mạn hoàn hảo cho các cặp đôi.",
    images: [
      "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800",
      "https://images.unsplash.com/photo-1570366583862-f91883984fde?w=800",
    ],
    category: "Núi",
    address: "Tỉnh Lâm Đồng, Việt Nam",
    latitude: 11.9404,
    longitude: 108.4583,
    rating: 4.4,
    reviewCount: 1678,
    priceRange: "2-5 triệu",
    tags: ["Hoa", "Thác nước", "Cà phê", "Lãng mạn"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Check-in tại Hồ Xuân Hương",
      "Tham quan vườn hoa thành phố",
      "Thưởng thức cà phê Đà Lạt",
      "Khám phá Thác Datanla bằng máng trượt",
      "Đi chợ đêm Đà Lạt",
    ],
    tips: [
      "Mang áo ấm vì trời lạnh về đêm",
      "Thuê xe máy là cách tốt nhất để khám phá",
      "Đừng bỏ lỡ bánh tráng nướng chợ đêm",
      "Săn mây Langbiang vào sáng sớm",
    ],
    bestTimeToVisit: "Tháng 11 - Tháng 3",
  },
  {
    id: "dest_8",
    name: "Kinh thành Huế",
    description:
      "Kinh thành Huế là pháo đài và cung điện có tường bao trong cố đô Việt Nam. Là Di sản Thế giới UNESCO, nơi đây từng là trung tâm quyền lực của triều Nguyễn từ 1802 đến 1945. Quần thể bao gồm Tử Cấm Thành, lăng tẩm hoàng gia và các ngôi chùa cổ.",
    images: [
      "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800",
      "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800",
    ],
    category: "Lịch sử",
    address: "Huế, Thừa Thiên Huế, Việt Nam",
    latitude: 16.4698,
    longitude: 107.5792,
    rating: 4.5,
    reviewCount: 1456,
    priceRange: "< 2 triệu",
    tags: ["UNESCO", "Cung điện", "Lịch sử", "Kiến trúc"],
    openHours: "7:00 - 17:30",
    isActive: true,
    highlights: [
      "Tham quan Đại Nội - Tử Cấm Thành",
      "Thăm các lăng tẩm: Minh Mạng, Tự Đức, Khải Định",
      "Du thuyền trên sông Hương",
      "Thưởng thức ẩm thực cung đình Huế",
      "Ngắm Cầu Trường Tiền về đêm",
    ],
    tips: [
      "Mua vé combo tham quan nhiều điểm tiết kiệm hơn",
      "Nên thuê hướng dẫn viên để hiểu lịch sử",
      "Thử bún bò Huế chính gốc",
      "Tránh giờ trưa nắng khi tham quan",
    ],
    bestTimeToVisit: "Tháng 1 - Tháng 4",
  },
  {
    id: "dest_9",
    name: "Nha Trang",
    description:
      "Nha Trang là thành phố biển phía nam Việt Nam nổi tiếng với bãi biển đẹp, các điểm lặn biển và đảo ngoài khơi. Thành phố có cuộc sống về đêm sôi động, nhà hàng hải sản và di tích Chăm cổ. VinWonders trên đảo Hòn Tre là điểm tham quan hàng đầu.",
    images: [
      "https://images.unsplash.com/photo-1559628376-f3fe5f782a2e?w=800",
      "https://images.unsplash.com/photo-1540611025311-01df3cee54b5?w=800",
    ],
    category: "Biển",
    address: "Tỉnh Khánh Hòa, Việt Nam",
    latitude: 12.2388,
    longitude: 109.1967,
    rating: 4.3,
    reviewCount: 1890,
    priceRange: "2-5 triệu",
    tags: ["Biển", "Lặn biển", "Đảo", "Giải trí đêm"],
    openHours: "Mở cửa 24 giờ",
    isActive: true,
    highlights: [
      "Lặn ngắm san hô tại Hòn Mun",
      "Tham quan VinWonders Nha Trang",
      "Tắm bùn khoáng nóng",
      "Tour 4 đảo bằng tàu",
      "Khám phá Tháp Bà Ponagar",
    ],
    tips: [
      "Mùa biển đẹp nhất từ tháng 6 đến tháng 9",
      "Nên đặt tour lặn biển trước",
      "Tắm bùn I-Resort là trải nghiệm phải thử",
      "Chợ Đầm là nơi mua hải sản tươi",
    ],
    bestTimeToVisit: "Tháng 6 - Tháng 9",
  },
  {
    id: "dest_10",
    name: "Phong Nha - Kẻ Bàng",
    description:
      "Vườn Quốc gia Phong Nha-Kẻ Bàng là Di sản Thế giới UNESCO, nơi có hang Sơn Đoòng - hang động lớn nhất thế giới. Vườn quốc gia sở hữu hệ thống hang động ngoạn mục, sông ngầm và rừng nguyên sinh. Những người yêu mạo hiểm có thể khám phá các hang động từ dễ đến hành trình nhiều ngày.",
    images: [
      "https://images.unsplash.com/photo-1573790387438-4da905039392?w=800",
      "https://images.unsplash.com/photo-1528127269322-539801943592?w=800",
    ],
    category: "Phiêu lưu",
    address: "Tỉnh Quảng Bình, Việt Nam",
    latitude: 17.5922,
    longitude: 106.2834,
    rating: 4.7,
    reviewCount: 987,
    priceRange: "5-10 triệu",
    tags: ["UNESCO", "Hang động", "Phiêu lưu", "Rừng"],
    openHours: "7:00 - 16:30",
    isActive: true,
    highlights: [
      "Khám phá Động Phong Nha bằng thuyền",
      "Tham quan Động Thiên Đường",
      "Zipline qua sông tại Dark Cave",
      "Trekking trong rừng quốc gia",
      "Tour hang Sơn Đoòng (đặt trước 1 năm)",
    ],
    tips: [
      "Đặt tour Sơn Đoòng cần trước 6-12 tháng",
      "Dark Cave là trải nghiệm vui nhất cho nhóm",
      "Mang đồ chống nước cho các hoạt động hang động",
      "Mùa khô tháng 4-8 là thời điểm tốt nhất",
    ],
    bestTimeToVisit: "Tháng 4 - Tháng 8",
  },
];

export const SEED_ADMIN: {
  username: string;
  password: string;
  email: string;
  fullName: string;
  role: "admin";
} = {
  username: "admin",
  password: "admin123",
  email: "admin@plango.vn",
  fullName: "PlanGo Admin",
  role: "admin",
};
